export const countries = [
  { code: "AD", country: "Andorra", flag: "🇦🇩", dial_code: "+376" },
  { code: "AE", country: "United Arab Emirates", flag: "🇦🇪", dial_code: "+971" },
  { code: "AF", country: "Afghanistan", flag: "🇦🇫", dial_code: "+93" },
  { code: "AG", country: "Antigua and Barbuda", flag: "🇦🇬", dial_code: "+1" },
  { code: "AI", country: "Anguilla", flag: "🇦🇮", dial_code: "+1" },
  { code: "AL", country: "Albania", flag: "🇦🇱", dial_code: "+355" },
  { code: "AM", country: "Armenia", flag: "🇦🇲", dial_code: "+374" },
  { code: "AO", country: "Angola", flag: "🇦🇴", dial_code: "+244" },
  { code: "AR", country: "Argentina", flag: "🇦🇷", dial_code: "+54" },
  { code: "AS", country: "American Samoa", flag: "🇦🇸", dial_code: "+1" },
  { code: "AT", country: "Austria", flag: "🇦🇹", dial_code: "+43" },
  { code: "AU", country: "Australia", flag: "🇦🇺", dial_code: "+61" },
  { code: "AW", country: "Aruba", flag: "🇦🇼", dial_code: "+297" },
  { code: "AZ", country: "Azerbaijan", flag: "🇦🇿", dial_code: "+994" },
  { code: "BA", country: "Bosnia and Herzegovina", flag: "🇧🇦", dial_code: "+387" },
  { code: "BB", country: "Barbados", flag: "🇧🇧", dial_code: "+1" },
  { code: "BD", country: "Bangladesh", flag: "🇧🇩", dial_code: "+880" },
  { code: "BE", country: "Belgium", flag: "🇧🇪", dial_code: "+32" },
  { code: "BF", country: "Burkina Faso", flag: "🇧🇫", dial_code: "+226" },
  { code: "BG", country: "Bulgaria", flag: "🇧🇬", dial_code: "+359" },
  { code: "BH", country: "Bahrain", flag: "🇧🇭", dial_code: "+973" },
  { code: "BI", country: "Burundi", flag: "🇧🇮", dial_code: "+257" },
  { code: "BJ", country: "Benin", flag: "🇧🇯", dial_code: "+229" },
  { code: "BM", country: "Bermuda", flag: "🇧🇲", dial_code: "+1" },
  { code: "BN", country: "Brunei", flag: "🇧🇳", dial_code: "+673" },
  { code: "BO", country: "Bolivia", flag: "🇧🇴", dial_code: "+591" },
  { code: "BR", country: "Brazil", flag: "🇧🇷", dial_code: "+55" },
  { code: "BS", country: "Bahamas", flag: "🇧🇸", dial_code: "+1" },
  { code: "BT", country: "Bhutan", flag: "🇧🇹", dial_code: "+975" },
  { code: "BW", country: "Botswana", flag: "🇧🇼", dial_code: "+267" },
  { code: "BY", country: "Belarus", flag: "🇧🇾", dial_code: "+375" },
  { code: "BZ", country: "Belize", flag: "🇧🇿", dial_code: "+501" },
  { code: "CA", country: "Canada", flag: "🇨🇦", dial_code: "+1" },
  { code: "CD", country: "Congo (DRC)", flag: "🇨🇩", dial_code: "+243" },
  { code: "CF", country: "Central African Republic", flag: "🇨🇫", dial_code: "+236" },
  { code: "CG", country: "Congo (Republic)", flag: "🇨🇬", dial_code: "+242" },
  { code: "CH", country: "Switzerland", flag: "🇨🇭", dial_code: "+41" },
  { code: "CI", country: "Côte d'Ivoire", flag: "🇨🇮", dial_code: "+225" },
  { code: "CK", country: "Cook Islands", flag: "🇨🇰", dial_code: "+682" },
  { code: "CL", country: "Chile", flag: "🇨🇱", dial_code: "+56" },
  { code: "CM", country: "Cameroon", flag: "🇨🇲", dial_code: "+237" },
  { code: "CN", country: "China", flag: "🇨🇳", dial_code: "+86" },
  { code: "CO", country: "Colombia", flag: "🇨🇴", dial_code: "+57" },
  { code: "CR", country: "Costa Rica", flag: "🇨🇷", dial_code: "+506" },
  { code: "CU", country: "Cuba", flag: "🇨🇺", dial_code: "+53" },
  { code: "CV", country: "Cape Verde", flag: "🇨🇻", dial_code: "+238" },
  { code: "CY", country: "Cyprus", flag: "🇨🇾", dial_code: "+357" },
  { code: "CZ", country: "Czech Republic", flag: "🇨🇿", dial_code: "+420" },
  { code: "DE", country: "Germany", flag: "🇩🇪", dial_code: "+49" },
  { code: "DJ", country: "Djibouti", flag: "🇩🇯", dial_code: "+253" },
  { code: "DK", country: "Denmark", flag: "🇩🇰", dial_code: "+45" },
  { code: "DM", country: "Dominica", flag: "🇩🇲", dial_code: "+1" },
  { code: "DO", country: "Dominican Republic", flag: "🇩🇴", dial_code: "+1" },
  { code: "DZ", country: "Algeria", flag: "🇩🇿", dial_code: "+213" },
  { code: "EC", country: "Ecuador", flag: "🇪🇨", dial_code: "+593" },
  { code: "EE", country: "Estonia", flag: "🇪🇪", dial_code: "+372" },
  { code: "EG", country: "Egypt", flag: "🇪🇬", dial_code: "+20" },
  { code: "ER", country: "Eritrea", flag: "🇪🇷", dial_code: "+291" },
  { code: "ES", country: "Spain", flag: "🇪🇸", dial_code: "+34" },
  { code: "ET", country: "Ethiopia", flag: "🇪🇹", dial_code: "+251" },
  { code: "FI", country: "Finland", flag: "🇫🇮", dial_code: "+358" },
  { code: "FJ", country: "Fiji", flag: "🇫🇯", dial_code: "+679" },
  { code: "FK", country: "Falkland Islands", flag: "🇫🇰", dial_code: "+500" },
  { code: "FM", country: "Micronesia", flag: "🇫🇲", dial_code: "+691" },
  { code: "FO", country: "Faroe Islands", flag: "🇫🇴", dial_code: "+298" },
  { code: "FR", country: "France", flag: "🇫🇷", dial_code: "+33" },
  { code: "GA", country: "Gabon", flag: "🇬🇦", dial_code: "+241" },
  { code: "GB", country: "United Kingdom", flag: "🇬🇧", dial_code: "+44" },
  { code: "GD", country: "Grenada", flag: "🇬🇩", dial_code: "+1" },
  { code: "GE", country: "Georgia", flag: "🇬🇪", dial_code: "+995" },
  { code: "GH", country: "Ghana", flag: "🇬🇭", dial_code: "+233" },
  { code: "GI", country: "Gibraltar", flag: "🇬🇮", dial_code: "+350" },
  { code: "GL", country: "Greenland", flag: "🇬🇱", dial_code: "+299" },
  { code: "GM", country: "Gambia", flag: "🇬🇲", dial_code: "+220" },
  { code: "GN", country: "Guinea", flag: "🇬🇳", dial_code: "+224" },
  { code: "GQ", country: "Equatorial Guinea", flag: "🇬🇶", dial_code: "+240" },
  { code: "GR", country: "Greece", flag: "🇬🇷", dial_code: "+30" },
  { code: "GT", country: "Guatemala", flag: "🇬🇹", dial_code: "+502" },
  { code: "GU", country: "Guam", flag: "🇬🇺", dial_code: "+1" },
  { code: "GW", country: "Guinea-Bissau", flag: "🇬🇼", dial_code: "+245" },
  { code: "GY", country: "Guyana", flag: "🇬🇾", dial_code: "+592" },
  { code: "HK", country: "Hong Kong", flag: "🇭🇰", dial_code: "+852" },
  { code: "HN", country: "Honduras", flag: "🇭🇳", dial_code: "+504" },
  { code: "HR", country: "Croatia", flag: "🇭🇷", dial_code: "+385" },
  { code: "HT", country: "Haiti", flag: "🇭🇹", dial_code: "+509" },
  { code: "HU", country: "Hungary", flag: "🇭🇺", dial_code: "+36" },
  { code: "ID", country: "Indonesia", flag: "🇮🇩", dial_code: "+62" },
  { code: "IE", country: "Ireland", flag: "🇮🇪", dial_code: "+353" },
  { code: "IL", country: "Israel", flag: "🇮🇱", dial_code: "+972" },
  { code: "IN", country: "India", flag: "🇮🇳", dial_code: "+91" },
  { code: "IQ", country: "Iraq", flag: "🇮🇶", dial_code: "+964" },
  { code: "IR", country: "Iran", flag: "🇮🇷", dial_code: "+98" },
  { code: "IS", country: "Iceland", flag: "🇮🇸", dial_code: "+354" },
  { code: "IT", country: "Italy", flag: "🇮🇹", dial_code: "+39" },
  { code: "JM", country: "Jamaica", flag: "🇯🇲", dial_code: "+1" },
  { code: "JO", country: "Jordan", flag: "🇯🇴", dial_code: "+962" },
  { code: "JP", country: "Japan", flag: "🇯🇵", dial_code: "+81" },
  { code: "KE", country: "Kenya", flag: "🇰🇪", dial_code: "+254" },
  { code: "KG", country: "Kyrgyzstan", flag: "🇰🇬", dial_code: "+996" },
  { code: "KH", country: "Cambodia", flag: "🇰🇭", dial_code: "+855" },
  { code: "KI", country: "Kiribati", flag: "🇰🇮", dial_code: "+686" },
  { code: "KM", country: "Comoros", flag: "🇰🇲", dial_code: "+269" },
  { code: "KN", country: "Saint Kitts and Nevis", flag: "🇰🇳", dial_code: "+1" },
  { code: "KP", country: "North Korea", flag: "🇰🇵", dial_code: "+850" },
  { code: "KR", country: "South Korea", flag: "🇰🇷", dial_code: "+82" },
  { code: "KW", country: "Kuwait", flag: "🇰🇼", dial_code: "+965" },
  { code: "KY", country: "Cayman Islands", flag: "🇰🇾", dial_code: "+1" },
  { code: "KZ", country: "Kazakhstan", flag: "🇰🇿", dial_code: "+7" },
  { code: "LA", country: "Laos", flag: "🇱🇦", dial_code: "+856" },
  { code: "LB", country: "Lebanon", flag: "🇱🇧", dial_code: "+961" },
  { code: "LC", country: "Saint Lucia", flag: "🇱🇨", dial_code: "+1" },
  { code: "LI", country: "Liechtenstein", flag: "🇱🇮", dial_code: "+423" },
  { code: "LK", country: "Sri Lanka", flag: "🇱🇰", dial_code: "+94" },
  { code: "LR", country: "Liberia", flag: "🇱🇷", dial_code: "+231" },
  { code: "LS", country: "Lesotho", flag: "🇱🇸", dial_code: "+266" },
  { code: "LT", country: "Lithuania", flag: "🇱🇹", dial_code: "+370" },
  { code: "LU", country: "Luxembourg", flag: "🇱🇺", dial_code: "+352" },
  { code: "LV", country: "Latvia", flag: "🇱🇻", dial_code: "+371" },
  { code: "LY", country: "Libya", flag: "🇱🇾", dial_code: "+218" },
  { code: "MA", country: "Morocco", flag: "🇲🇦", dial_code: "+212" },
  { code: "MC", country: "Monaco", flag: "🇲🇨", dial_code: "+377" },
  { code: "MD", country: "Moldova", flag: "🇲🇩", dial_code: "+373" },
  { code: "ME", country: "Montenegro", flag: "🇲🇪", dial_code: "+382" },
  { code: "MG", country: "Madagascar", flag: "🇲🇬", dial_code: "+261" },
  { code: "MH", country: "Marshall Islands", flag: "🇲🇭", dial_code: "+692" },
  { code: "MK", country: "North Macedonia", flag: "🇲🇰", dial_code: "+389" },
  { code: "ML", country: "Mali", flag: "🇲🇱", dial_code: "+223" },
  { code: "MM", country: "Myanmar", flag: "🇲🇲", dial_code: "+95" },
  { code: "MN", country: "Mongolia", flag: "🇲🇳", dial_code: "+976" },
  { code: "MO", country: "Macau", flag: "🇲🇴", dial_code: "+853" },
  { code: "MP", country: "Northern Mariana Islands", flag: "🇲🇵", dial_code: "+1" },
  { code: "MR", country: "Mauritania", flag: "🇲🇷", dial_code: "+222" },
  { code: "MS", country: "Montserrat", flag: "🇲🇸", dial_code: "+1" },
  { code: "MT", country: "Malta", flag: "🇲🇹", dial_code: "+356" },
  { code: "MU", country: "Mauritius", flag: "🇲🇺", dial_code: "+230" },
  { code: "MV", country: "Maldives", flag: "🇲🇻", dial_code: "+960" },
  { code: "MW", country: "Malawi", flag: "🇲🇼", dial_code: "+265" },
  { code: "MX", country: "Mexico", flag: "🇲🇽", dial_code: "+52" },
  { code: "MY", country: "Malaysia", flag: "🇲🇾", dial_code: "+60" },
  { code: "MZ", country: "Mozambique", flag: "🇲🇿", dial_code: "+258" },
  { code: "NA", country: "Namibia", flag: "🇳🇦", dial_code: "+264" },
  { code: "NE", country: "Niger", flag: "🇳🇪", dial_code: "+227" },
  { code: "NG", country: "Nigeria", flag: "🇳🇬", dial_code: "+234" },
  { code: "NI", country: "Nicaragua", flag: "🇳🇮", dial_code: "+505" },
  { code: "NL", country: "Netherlands", flag: "🇳🇱", dial_code: "+31" },
  { code: "NO", country: "Norway", flag: "🇳🇴", dial_code: "+47" },
  { code: "NP", country: "Nepal", flag: "🇳🇵", dial_code: "+977" },
  { code: "NR", country: "Nauru", flag: "🇳🇷", dial_code: "+674" },
  { code: "NU", country: "Niue", flag: "🇳🇺", dial_code: "+683" },
  { code: "NZ", country: "New Zealand", flag: "🇳🇿", dial_code: "+64" },
  { code: "OM", country: "Oman", flag: "🇴🇲", dial_code: "+968" },
  { code: "PA", country: "Panama", flag: "🇵🇦", dial_code: "+507" },
  { code: "PE", country: "Peru", flag: "🇵🇪", dial_code: "+51" },
  { code: "PF", country: "French Polynesia", flag: "🇵🇫", dial_code: "+689" },
  { code: "PG", country: "Papua New Guinea", flag: "🇵🇬", dial_code: "+675" },
  { code: "PH", country: "Philippines", flag: "🇵🇭", dial_code: "+63" },
  { code: "PK", country: "Pakistan", flag: "🇵🇰", dial_code: "+92" },
  { code: "PL", country: "Poland", flag: "🇵🇱", dial_code: "+48" },
  { code: "PT", country: "Portugal", flag: "🇵🇹", dial_code: "+351" },
  { code: "PW", country: "Palau", flag: "🇵🇼", dial_code: "+680" },
  { code: "PY", country: "Paraguay", flag: "🇵🇾", dial_code: "+595" },
  { code: "QA", country: "Qatar", flag: "🇶🇦", dial_code: "+974" },
  { code: "RO", country: "Romania", flag: "🇷🇴", dial_code: "+40" },
  { code: "RS", country: "Serbia", flag: "🇷🇸", dial_code: "+381" },
  { code: "RU", country: "Russia", flag: "🇷🇺", dial_code: "+7" },
  { code: "RW", country: "Rwanda", flag: "🇷🇼", dial_code: "+250" },
  { code: "SA", country: "Saudi Arabia", flag: "🇸🇦", dial_code: "+966" },
  { code: "SB", country: "Solomon Islands", flag: "🇸🇧", dial_code: "+677" },
  { code: "SC", country: "Seychelles", flag: "🇸🇨", dial_code: "+248" },
  { code: "SD", country: "Sudan", flag: "🇸🇩", dial_code: "+249" },
  { code: "SE", country: "Sweden", flag: "🇸🇪", dial_code: "+46" },
  { code: "SG", country: "Singapore", flag: "🇸🇬", dial_code: "+65" },
  { code: "SI", country: "Slovenia", flag: "🇸🇮", dial_code: "+386" },
  { code: "SK", country: "Slovakia", flag: "🇸🇰", dial_code: "+421" },
  { code: "SL", country: "Sierra Leone", flag: "🇸🇱", dial_code: "+232" },
  { code: "SM", country: "San Marino", flag: "🇸🇲", dial_code: "+378" },
  { code: "SN", country: "Senegal", flag: "🇸🇳", dial_code: "+221" },
  { code: "SO", country: "Somalia", flag: "🇸🇴", dial_code: "+252" },
  { code: "SR", country: "Suriname", flag: "🇸🇷", dial_code: "+597" },
  { code: "ST", country: "São Tomé and Príncipe", flag: "🇸🇹", dial_code: "+239" },
  { code: "SV", country: "El Salvador", flag: "🇸🇻", dial_code: "+503" },
  { code: "SY", country: "Syria", flag: "🇸🇾", dial_code: "+963" },
  { code: "SZ", country: "Eswatini", flag: "🇸🇿", dial_code: "+268" },
  { code: "TC", country: "Turks and Caicos Islands", flag: "🇹🇨", dial_code: "+1" },
  { code: "TD", country: "Chad", flag: "🇹🇩", dial_code: "+235" },
  { code: "TG", country: "Togo", flag: "🇹🇬", dial_code: "+228" },
  { code: "TH", country: "Thailand", flag: "🇹🇭", dial_code: "+66" },
  { code: "TJ", country: "Tajikistan", flag: "🇹🇯", dial_code: "+992" },
  { code: "TL", country: "Timor-Leste", flag: "🇹🇱", dial_code: "+670" },
  { code: "TM", country: "Turkmenistan", flag: "🇹🇲", dial_code: "+993" },
  { code: "TN", country: "Tunisia", flag: "🇹🇳", dial_code: "+216" },
  { code: "TO", country: "Tonga", flag: "🇹🇴", dial_code: "+676" },
  { code: "TR", country: "Turkey", flag: "🇹🇷", dial_code: "+90" },
  { code: "TT", country: "Trinidad and Tobago", flag: "🇹🇹", dial_code: "+1" },
  { code: "TV", country: "Tuvalu", flag: "🇹🇻", dial_code: "+688" },
  { code: "TW", country: "Taiwan", flag: "🇹🇼", dial_code: "+886" },
  { code: "TZ", country: "Tanzania", flag: "🇹🇿", dial_code: "+255" },
  { code: "UA", country: "Ukraine", flag: "🇺🇦", dial_code: "+380" },
  { code: "UG", country: "Uganda", flag: "🇺🇬", dial_code: "+256" },
  { code: "US", country: "United States", flag: "🇺🇸", dial_code: "+1" },
  { code: "UY", country: "Uruguay", flag: "🇺🇾", dial_code: "+598" },
  { code: "UZ", country: "Uzbekistan", flag: "🇺🇿", dial_code: "+998" },
  { code: "VA", country: "Vatican City", flag: "🇻🇦", dial_code: "+39" },
  { code: "VC", country: "Saint Vincent and the Grenadines", flag: "🇻🇨", dial_code: "+1" },
  { code: "VE", country: "Venezuela", flag: "🇻🇪", dial_code: "+58" },
  { code: "VG", country: "British Virgin Islands", flag: "🇻🇬", dial_code: "+1" },
  { code: "VI", country: "U.S. Virgin Islands", flag: "🇻🇮", dial_code: "+1" },
  { code: "VN", country: "Vietnam", flag: "🇻🇳", dial_code: "+84" },
  { code: "VU", country: "Vanuatu", flag: "🇻🇺", dial_code: "+678" },
  { code: "WS", country: "Samoa", flag: "🇼🇸", dial_code: "+685" },
  { code: "YE", country: "Yemen", flag: "🇾🇪", dial_code: "+967" },
  { code: "ZA", country: "South Africa", flag: "🇿🇦", dial_code: "+27" },
  { code: "ZM", country: "Zambia", flag: "🇿🇲", dial_code: "+260" },
  { code: "ZW", country: "Zimbabwe", flag: "🇿🇼", dial_code: "+263" },
]
